name: Build and Deploy Documentation

on:
  push:
    branches:
      - astrojoni89-patch-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"
        
    - name: Install dependencies
      run: |
        pip install -e .

    - name: Build Documentation
      run: |
        git checkout -B gh_pages
        sphinx-build -b html docs/ docs/build/

    - name: Deploy to gh-pages
      run: |
        git add -f docs/build/
        git commit -m "Update docs"
        git push -f origin gh_pages
